/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

#include <a_samp>

new Text:PublicTD[21];
new PlayerText:PlayerTD[MAX_PLAYERS][14];

public OnFilterScriptInit()
{
	PublicTD[0] = TextDrawCreate(315.000000, 105.000000, "ld_dual:white");
	TextDrawFont(PublicTD[0], 4);
	TextDrawLetterSize(PublicTD[0], 0.600000, 2.000000);
	TextDrawTextSize(PublicTD[0], 310.000000, 280.000000);
	TextDrawSetOutline(PublicTD[0], 1);
	TextDrawSetShadow(PublicTD[0], 0);
	TextDrawAlignment(PublicTD[0], 1);
	TextDrawColor(PublicTD[0], 170);
	TextDrawBackgroundColor(PublicTD[0], 255);
	TextDrawBoxColor(PublicTD[0], 50);
	TextDrawUseBox(PublicTD[0], 1);
	TextDrawSetProportional(PublicTD[0], 1);
	TextDrawSetSelectable(PublicTD[0], 0);

	PublicTD[1] = TextDrawCreate(315.000000, 105.000000, "ld_dual:white");
	TextDrawFont(PublicTD[1], 4);
	TextDrawLetterSize(PublicTD[1], 0.600000, 2.000000);
	TextDrawTextSize(PublicTD[1], 310.000000, 30.000000);
	TextDrawSetOutline(PublicTD[1], 1);
	TextDrawSetShadow(PublicTD[1], 0);
	TextDrawAlignment(PublicTD[1], 1);
	TextDrawColor(PublicTD[1], 1097458175);
	TextDrawBackgroundColor(PublicTD[1], 255);
	TextDrawBoxColor(PublicTD[1], 50);
	TextDrawUseBox(PublicTD[1], 1);
	TextDrawSetProportional(PublicTD[1], 1);
	TextDrawSetSelectable(PublicTD[1], 0);

	PublicTD[2] = TextDrawCreate(480.000000, 111.000000, "EDITOR DE ACESSORIOS");
	TextDrawFont(PublicTD[2], 2);
	TextDrawLetterSize(PublicTD[2], 0.449999, 1.799998);
	TextDrawTextSize(PublicTD[2], 400.000000, 319.500000);
	TextDrawSetOutline(PublicTD[2], 0);
	TextDrawSetShadow(PublicTD[2], 0);
	TextDrawAlignment(PublicTD[2], 2);
	TextDrawColor(PublicTD[2], -1);
	TextDrawBackgroundColor(PublicTD[2], 255);
	TextDrawBoxColor(PublicTD[2], 50);
	TextDrawUseBox(PublicTD[2], 0);
	TextDrawSetProportional(PublicTD[2], 1);
	TextDrawSetSelectable(PublicTD[2], 0);

	PublicTD[3] = TextDrawCreate(375.000000, 150.000000, "ld_beat:left");
	TextDrawFont(PublicTD[3], 4);
	TextDrawLetterSize(PublicTD[3], 0.600000, 2.000000);
	TextDrawTextSize(PublicTD[3], 50.000000, 50.000000);
	TextDrawSetOutline(PublicTD[3], 1);
	TextDrawSetShadow(PublicTD[3], 0);
	TextDrawAlignment(PublicTD[3], 1);
	TextDrawColor(PublicTD[3], -1);
	TextDrawBackgroundColor(PublicTD[3], 255);
	TextDrawBoxColor(PublicTD[3], 50);
	TextDrawUseBox(PublicTD[3], 1);
	TextDrawSetProportional(PublicTD[3], 1);
	TextDrawSetSelectable(PublicTD[3], 1);

	PublicTD[4] = TextDrawCreate(375.000000, 210.000000, "ld_beat:left");
	TextDrawFont(PublicTD[4], 4);
	TextDrawLetterSize(PublicTD[4], 0.600000, 2.000000);
	TextDrawTextSize(PublicTD[4], 50.000000, 50.000000);
	TextDrawSetOutline(PublicTD[4], 1);
	TextDrawSetShadow(PublicTD[4], 0);
	TextDrawAlignment(PublicTD[4], 1);
	TextDrawColor(PublicTD[4], -1);
	TextDrawBackgroundColor(PublicTD[4], 255);
	TextDrawBoxColor(PublicTD[4], 50);
	TextDrawUseBox(PublicTD[4], 1);
	TextDrawSetProportional(PublicTD[4], 1);
	TextDrawSetSelectable(PublicTD[4], 1);

	PublicTD[5] = TextDrawCreate(375.000000, 270.000000, "ld_beat:left");
	TextDrawFont(PublicTD[5], 4);
	TextDrawLetterSize(PublicTD[5], 0.600000, 2.000000);
	TextDrawTextSize(PublicTD[5], 50.000000, 50.000000);
	TextDrawSetOutline(PublicTD[5], 1);
	TextDrawSetShadow(PublicTD[5], 0);
	TextDrawAlignment(PublicTD[5], 1);
	TextDrawColor(PublicTD[5], -1);
	TextDrawBackgroundColor(PublicTD[5], 255);
	TextDrawBoxColor(PublicTD[5], 50);
	TextDrawUseBox(PublicTD[5], 1);
	TextDrawSetProportional(PublicTD[5], 1);
	TextDrawSetSelectable(PublicTD[5], 1);

	PublicTD[6] = TextDrawCreate(565.000000, 150.000000, "ld_beat:right");
	TextDrawFont(PublicTD[6], 4);
	TextDrawLetterSize(PublicTD[6], 0.600000, 2.000000);
	TextDrawTextSize(PublicTD[6], 50.000000, 50.000000);
	TextDrawSetOutline(PublicTD[6], 1);
	TextDrawSetShadow(PublicTD[6], 0);
	TextDrawAlignment(PublicTD[6], 1);
	TextDrawColor(PublicTD[6], -1);
	TextDrawBackgroundColor(PublicTD[6], 255);
	TextDrawBoxColor(PublicTD[6], 50);
	TextDrawUseBox(PublicTD[6], 1);
	TextDrawSetProportional(PublicTD[6], 1);
	TextDrawSetSelectable(PublicTD[6], 1);

	PublicTD[7] = TextDrawCreate(565.000000, 210.000000, "ld_beat:right");
	TextDrawFont(PublicTD[7], 4);
	TextDrawLetterSize(PublicTD[7], 0.600000, 2.000000);
	TextDrawTextSize(PublicTD[7], 50.000000, 50.000000);
	TextDrawSetOutline(PublicTD[7], 1);
	TextDrawSetShadow(PublicTD[7], 0);
	TextDrawAlignment(PublicTD[7], 1);
	TextDrawColor(PublicTD[7], -1);
	TextDrawBackgroundColor(PublicTD[7], 255);
	TextDrawBoxColor(PublicTD[7], 50);
	TextDrawUseBox(PublicTD[7], 1);
	TextDrawSetProportional(PublicTD[7], 1);
	TextDrawSetSelectable(PublicTD[7], 1);

	PublicTD[8] = TextDrawCreate(565.000000, 270.000000, "ld_beat:right");
	TextDrawFont(PublicTD[8], 4);
	TextDrawLetterSize(PublicTD[8], 0.600000, 2.000000);
	TextDrawTextSize(PublicTD[8], 50.000000, 50.000000);
	TextDrawSetOutline(PublicTD[8], 1);
	TextDrawSetShadow(PublicTD[8], 0);
	TextDrawAlignment(PublicTD[8], 1);
	TextDrawColor(PublicTD[8], -1);
	TextDrawBackgroundColor(PublicTD[8], 255);
	TextDrawBoxColor(PublicTD[8], 50);
	TextDrawUseBox(PublicTD[8], 1);
	TextDrawSetProportional(PublicTD[8], 1);
	TextDrawSetSelectable(PublicTD[8], 1);

	PublicTD[9] = TextDrawCreate(500.000000, 335.000000, "ld_dual:white");
	TextDrawFont(PublicTD[9], 4);
	TextDrawLetterSize(PublicTD[9], 0.600000, 2.000000);
	TextDrawTextSize(PublicTD[9], 115.000000, 40.000000);
	TextDrawSetOutline(PublicTD[9], 1);
	TextDrawSetShadow(PublicTD[9], 0);
	TextDrawAlignment(PublicTD[9], 1);
	TextDrawColor(PublicTD[9], 852308735);
	TextDrawBackgroundColor(PublicTD[9], 255);
	TextDrawBoxColor(PublicTD[9], 50);
	TextDrawUseBox(PublicTD[9], 1);
	TextDrawSetProportional(PublicTD[9], 1);
	TextDrawSetSelectable(PublicTD[9], 1);

	PublicTD[10] = TextDrawCreate(375.000000, 335.000000, "ld_dual:white");
	TextDrawFont(PublicTD[10], 4);
	TextDrawLetterSize(PublicTD[10], 0.600000, 2.000000);
	TextDrawTextSize(PublicTD[10], 115.000000, 40.000000);
	TextDrawSetOutline(PublicTD[10], 1);
	TextDrawSetShadow(PublicTD[10], 0);
	TextDrawAlignment(PublicTD[10], 1);
	TextDrawColor(PublicTD[10], -764862721);
	TextDrawBackgroundColor(PublicTD[10], 255);
	TextDrawBoxColor(PublicTD[10], 50);
	TextDrawUseBox(PublicTD[10], 1);
	TextDrawSetProportional(PublicTD[10], 1);
	TextDrawSetSelectable(PublicTD[10], 1);

	PublicTD[11] = TextDrawCreate(315.000000, 73.000000, "ld_dual:white");
	TextDrawFont(PublicTD[11], 4);
	TextDrawLetterSize(PublicTD[11], 0.600000, 2.000000);
	TextDrawTextSize(PublicTD[11], 32.000000, 32.000000);
	TextDrawSetOutline(PublicTD[11], 1);
	TextDrawSetShadow(PublicTD[11], 0);
	TextDrawAlignment(PublicTD[11], 1);
	TextDrawColor(PublicTD[11], -13421569);
	TextDrawBackgroundColor(PublicTD[11], 255);
	TextDrawBoxColor(PublicTD[11], 50);
	TextDrawUseBox(PublicTD[11], 1);
	TextDrawSetProportional(PublicTD[11], 1);
	TextDrawSetSelectable(PublicTD[11], 1);

	PublicTD[12] = TextDrawCreate(331.500000, 80.000000, "X");
	TextDrawFont(PublicTD[12], 2);
	TextDrawLetterSize(PublicTD[12], 0.449999, 1.799998);
	TextDrawTextSize(PublicTD[12], 400.000000, 183.000000);
	TextDrawSetOutline(PublicTD[12], 0);
	TextDrawSetShadow(PublicTD[12], 0);
	TextDrawAlignment(PublicTD[12], 2);
	TextDrawColor(PublicTD[12], -1);
	TextDrawBackgroundColor(PublicTD[12], 255);
	TextDrawBoxColor(PublicTD[12], 50);
	TextDrawUseBox(PublicTD[12], 0);
	TextDrawSetProportional(PublicTD[12], 1);
	TextDrawSetSelectable(PublicTD[12], 0);

	PublicTD[13] = TextDrawCreate(495.000000, 190.000000, "- posicao +");
	TextDrawFont(PublicTD[13], 2);
	TextDrawLetterSize(PublicTD[13], 0.300000, 1.200000);
	TextDrawTextSize(PublicTD[13], 400.000000, 183.000000);
	TextDrawSetOutline(PublicTD[13], 0);
	TextDrawSetShadow(PublicTD[13], 0);
	TextDrawAlignment(PublicTD[13], 2);
	TextDrawColor(PublicTD[13], -1);
	TextDrawBackgroundColor(PublicTD[13], 255);
	TextDrawBoxColor(PublicTD[13], 50);
	TextDrawUseBox(PublicTD[13], 0);
	TextDrawSetProportional(PublicTD[13], 1);
	TextDrawSetSelectable(PublicTD[13], 0);

	PublicTD[14] = TextDrawCreate(500.000000, 157.500000, "ld_dual:white");
	TextDrawFont(PublicTD[14], 4);
	TextDrawLetterSize(PublicTD[14], 0.600000, 2.000000);
	TextDrawTextSize(PublicTD[14], 60.000000, 30.000000);
	TextDrawSetOutline(PublicTD[14], 1);
	TextDrawSetShadow(PublicTD[14], 0);
	TextDrawAlignment(PublicTD[14], 1);
	TextDrawColor(PublicTD[14], 144);
	TextDrawBackgroundColor(PublicTD[14], 255);
	TextDrawBoxColor(PublicTD[14], 50);
	TextDrawUseBox(PublicTD[14], 1);
	TextDrawSetProportional(PublicTD[14], 1);
	TextDrawSetSelectable(PublicTD[14], 1);

	PublicTD[15] = TextDrawCreate(500.000000, 217.500000, "ld_dual:white");
	TextDrawFont(PublicTD[15], 4);
	TextDrawLetterSize(PublicTD[15], 0.600000, 2.000000);
	TextDrawTextSize(PublicTD[15], 60.000000, 30.000000);
	TextDrawSetOutline(PublicTD[15], 1);
	TextDrawSetShadow(PublicTD[15], 0);
	TextDrawAlignment(PublicTD[15], 1);
	TextDrawColor(PublicTD[15], 144);
	TextDrawBackgroundColor(PublicTD[15], 255);
	TextDrawBoxColor(PublicTD[15], 50);
	TextDrawUseBox(PublicTD[15], 1);
	TextDrawSetProportional(PublicTD[15], 1);
	TextDrawSetSelectable(PublicTD[15], 1);

	PublicTD[16] = TextDrawCreate(500.000000, 277.500000, "ld_dual:white");
	TextDrawFont(PublicTD[16], 4);
	TextDrawLetterSize(PublicTD[16], 0.600000, 2.000000);
	TextDrawTextSize(PublicTD[16], 60.000000, 30.000000);
	TextDrawSetOutline(PublicTD[16], 1);
	TextDrawSetShadow(PublicTD[16], 0);
	TextDrawAlignment(PublicTD[16], 1);
	TextDrawColor(PublicTD[16], 144);
	TextDrawBackgroundColor(PublicTD[16], 255);
	TextDrawBoxColor(PublicTD[16], 50);
	TextDrawUseBox(PublicTD[16], 1);
	TextDrawSetProportional(PublicTD[16], 1);
	TextDrawSetSelectable(PublicTD[16], 1);

	PublicTD[17] = TextDrawCreate(495.000000, 250.000000, "- ROTACAO +");
	TextDrawFont(PublicTD[17], 2);
	TextDrawLetterSize(PublicTD[17], 0.300000, 1.200000);
	TextDrawTextSize(PublicTD[17], 400.000000, 183.000000);
	TextDrawSetOutline(PublicTD[17], 0);
	TextDrawSetShadow(PublicTD[17], 0);
	TextDrawAlignment(PublicTD[17], 2);
	TextDrawColor(PublicTD[17], -1);
	TextDrawBackgroundColor(PublicTD[17], 255);
	TextDrawBoxColor(PublicTD[17], 50);
	TextDrawUseBox(PublicTD[17], 0);
	TextDrawSetProportional(PublicTD[17], 1);
	TextDrawSetSelectable(PublicTD[17], 0);

	PublicTD[18] = TextDrawCreate(495.000000, 310.000000, "- ESCALA +");
	TextDrawFont(PublicTD[18], 2);
	TextDrawLetterSize(PublicTD[18], 0.300000, 1.200000);
	TextDrawTextSize(PublicTD[18], 400.000000, 183.000000);
	TextDrawSetOutline(PublicTD[18], 0);
	TextDrawSetShadow(PublicTD[18], 0);
	TextDrawAlignment(PublicTD[18], 2);
	TextDrawColor(PublicTD[18], -1);
	TextDrawBackgroundColor(PublicTD[18], 255);
	TextDrawBoxColor(PublicTD[18], 50);
	TextDrawUseBox(PublicTD[18], 0);
	TextDrawSetProportional(PublicTD[18], 1);
	TextDrawSetSelectable(PublicTD[18], 0);

	PublicTD[19] = TextDrawCreate(557.500000, 349.500000, "SALVAR");
	TextDrawFont(PublicTD[19], 2);
	TextDrawLetterSize(PublicTD[19], 0.300000, 1.200000);
	TextDrawTextSize(PublicTD[19], 400.000000, 183.000000);
	TextDrawSetOutline(PublicTD[19], 0);
	TextDrawSetShadow(PublicTD[19], 0);
	TextDrawAlignment(PublicTD[19], 2);
	TextDrawColor(PublicTD[19], -1);
	TextDrawBackgroundColor(PublicTD[19], 255);
	TextDrawBoxColor(PublicTD[19], 50);
	TextDrawUseBox(PublicTD[19], 0);
	TextDrawSetProportional(PublicTD[19], 1);
	TextDrawSetSelectable(PublicTD[19], 0);

	PublicTD[20] = TextDrawCreate(432.500000, 349.500000, "ALTERAR VISAO");
	TextDrawFont(PublicTD[20], 2);
	TextDrawLetterSize(PublicTD[20], 0.300000, 1.200000);
	TextDrawTextSize(PublicTD[20], 400.000000, 183.000000);
	TextDrawSetOutline(PublicTD[20], 0);
	TextDrawSetShadow(PublicTD[20], 0);
	TextDrawAlignment(PublicTD[20], 2);
	TextDrawColor(PublicTD[20], -1);
	TextDrawBackgroundColor(PublicTD[20], 255);
	TextDrawBoxColor(PublicTD[20], 50);
	TextDrawUseBox(PublicTD[20], 0);
	TextDrawSetProportional(PublicTD[20], 1);
	TextDrawSetSelectable(PublicTD[20], 0);

	return 1;
}

public OnFilterScriptExit()
{
	TextDrawDestroy(PublicTD[0]);
	TextDrawDestroy(PublicTD[1]);
	TextDrawDestroy(PublicTD[2]);
	TextDrawDestroy(PublicTD[3]);
	TextDrawDestroy(PublicTD[4]);
	TextDrawDestroy(PublicTD[5]);
	TextDrawDestroy(PublicTD[6]);
	TextDrawDestroy(PublicTD[7]);
	TextDrawDestroy(PublicTD[8]);
	TextDrawDestroy(PublicTD[9]);
	TextDrawDestroy(PublicTD[10]);
	TextDrawDestroy(PublicTD[11]);
	TextDrawDestroy(PublicTD[12]);
	TextDrawDestroy(PublicTD[13]);
	TextDrawDestroy(PublicTD[14]);
	TextDrawDestroy(PublicTD[15]);
	TextDrawDestroy(PublicTD[16]);
	TextDrawDestroy(PublicTD[17]);
	TextDrawDestroy(PublicTD[18]);
	TextDrawDestroy(PublicTD[19]);
	TextDrawDestroy(PublicTD[20]);
	return 1;
}

public OnPlayerConnect(playerid)
{
	PlayerTD[playerid][0] = CreatePlayerTextDraw(playerid, 315.000000, 185.000000, "Preview_Model");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][0], 5);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][0], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][0], 50.000000, 50.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][0], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][0], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][0], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][0], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][0], -131);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][0], 255);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][0], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][0], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][0], 1);
	PlayerTextDrawSetPreviewModel(playerid, PlayerTD[playerid][0], 18631);
	PlayerTextDrawSetPreviewRot(playerid, PlayerTD[playerid][0], 0.000000, 0.000000, 90.000000, 0.750000);
	PlayerTextDrawSetPreviewVehCol(playerid, PlayerTD[playerid][0], 0, 0);

	PlayerTD[playerid][1] = CreatePlayerTextDraw(playerid, 315.000000, 135.000000, "Preview_Model");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][1], 5);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][1], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][1], 50.000000, 50.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][1], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][1], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][1], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][1], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][1], -131);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][1], 255);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][1], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][1], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][1], 1);
	PlayerTextDrawSetPreviewModel(playerid, PlayerTD[playerid][1], 18631);
	PlayerTextDrawSetPreviewRot(playerid, PlayerTD[playerid][1], 0.000000, 0.000000, 90.000000, 0.750000);
	PlayerTextDrawSetPreviewVehCol(playerid, PlayerTD[playerid][1], 0, 0);

	PlayerTD[playerid][2] = CreatePlayerTextDraw(playerid, 315.000000, 235.000000, "Preview_Model");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][2], 5);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][2], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][2], 50.000000, 50.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][2], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][2], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][2], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][2], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][2], -131);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][2], 255);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][2], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][2], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][2], 1);
	PlayerTextDrawSetPreviewModel(playerid, PlayerTD[playerid][2], 18631);
	PlayerTextDrawSetPreviewRot(playerid, PlayerTD[playerid][2], 0.000000, 0.000000, 90.000000, 0.750000);
	PlayerTextDrawSetPreviewVehCol(playerid, PlayerTD[playerid][2], 0, 0);

	PlayerTD[playerid][3] = CreatePlayerTextDraw(playerid, 530.000000, 162.500000, "OFFSET:~n~9.9999");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][3], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][3], 0.250000, 1.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][3], 400.000000, 183.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][3], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][3], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][3], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][3], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][3], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][3], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][3], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][3], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][3], 0);

	PlayerTD[playerid][4] = CreatePlayerTextDraw(playerid, 530.000000, 222.500000, "OFFSET:~n~9.9999");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][4], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][4], 0.250000, 1.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][4], 400.000000, 183.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][4], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][4], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][4], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][4], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][4], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][4], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][4], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][4], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][4], 0);

	PlayerTD[playerid][5] = CreatePlayerTextDraw(playerid, 530.000000, 282.500000, "OFFSET:~n~9.9999");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][5], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][5], 0.250000, 1.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][5], 400.000000, 183.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][5], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][5], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][5], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][5], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][5], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][5], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][5], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][5], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][5], 0);

	PlayerTD[playerid][6] = CreatePlayerTextDraw(playerid, 315.000000, 285.000000, "Preview_Model");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][6], 5);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][6], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][6], 50.000000, 50.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][6], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][6], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][6], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][6], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][6], -131);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][6], 255);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][6], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][6], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][6], 1);
	PlayerTextDrawSetPreviewModel(playerid, PlayerTD[playerid][6], 18631);
	PlayerTextDrawSetPreviewRot(playerid, PlayerTD[playerid][6], 0.000000, 0.000000, 90.000000, 0.750000);
	PlayerTextDrawSetPreviewVehCol(playerid, PlayerTD[playerid][6], 0, 0);

	PlayerTD[playerid][7] = CreatePlayerTextDraw(playerid, 315.000000, 335.000000, "Preview_Model");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][7], 5);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][7], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][7], 50.000000, 50.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][7], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][7], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][7], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][7], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][7], -131);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][7], 255);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][7], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][7], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][7], 1);
	PlayerTextDrawSetPreviewModel(playerid, PlayerTD[playerid][7], 18631);
	PlayerTextDrawSetPreviewRot(playerid, PlayerTD[playerid][7], 0.000000, 0.000000, 90.000000, 0.750000);
	PlayerTextDrawSetPreviewVehCol(playerid, PlayerTD[playerid][7], 0, 0);

	PlayerTD[playerid][8] = CreatePlayerTextDraw(playerid, 430.000000, 157.500000, "ld_dual:white");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][8], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][8], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][8], 60.000000, 30.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][8], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][8], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][8], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][8], -16777072);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][8], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][8], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][8], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][8], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][8], 1);

	PlayerTD[playerid][9] = CreatePlayerTextDraw(playerid, 430.000000, 217.500000, "ld_dual:white");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][9], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][9], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][9], 60.000000, 30.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][9], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][9], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][9], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][9], 16711824);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][9], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][9], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][9], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][9], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][9], 1);

	PlayerTD[playerid][10] = CreatePlayerTextDraw(playerid, 430.000000, 277.500000, "ld_dual:white");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][10], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][10], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][10], 60.000000, 30.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][10], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][10], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][10], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][10], 65424);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][10], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][10], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][10], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][10], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][10], 1);

	PlayerTD[playerid][11] = CreatePlayerTextDraw(playerid, 460.000000, 167.500000, "EIXO X");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][11], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][11], 0.250000, 1.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][11], 400.000000, 183.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][11], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][11], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][11], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][11], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][11], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][11], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][11], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][11], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][11], 0);

	PlayerTD[playerid][12] = CreatePlayerTextDraw(playerid, 460.000000, 227.500000, "EIXO Y");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][12], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][12], 0.250000, 1.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][12], 400.000000, 183.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][12], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][12], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][12], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][12], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][12], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][12], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][12], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][12], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][12], 0);

	PlayerTD[playerid][13] = CreatePlayerTextDraw(playerid, 460.000000, 287.500000, "EIXO Z");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][13], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][13], 0.250000, 1.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][13], 400.000000, 183.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][13], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][13], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][13], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][13], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][13], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][13], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][13], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][13], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][13], 0);

	return 1;
}

public OnPlayerDisconnect(playerid, reason)
{
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][0]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][1]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][2]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][3]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][4]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][5]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][6]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][7]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][8]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][9]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][10]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][11]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][12]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][13]);
	return 1;
}

public OnPlayerCommandText(playerid, cmdtext[])
{
	if(!strcmp(cmdtext, "/tdtest", true))
	{
		TextDrawShowForPlayer(playerid, PublicTD[0]);
		TextDrawShowForPlayer(playerid, PublicTD[1]);
		TextDrawShowForPlayer(playerid, PublicTD[2]);
		TextDrawShowForPlayer(playerid, PublicTD[3]);
		TextDrawShowForPlayer(playerid, PublicTD[4]);
		TextDrawShowForPlayer(playerid, PublicTD[5]);
		TextDrawShowForPlayer(playerid, PublicTD[6]);
		TextDrawShowForPlayer(playerid, PublicTD[7]);
		TextDrawShowForPlayer(playerid, PublicTD[8]);
		TextDrawShowForPlayer(playerid, PublicTD[9]);
		TextDrawShowForPlayer(playerid, PublicTD[10]);
		TextDrawShowForPlayer(playerid, PublicTD[11]);
		TextDrawShowForPlayer(playerid, PublicTD[12]);
		TextDrawShowForPlayer(playerid, PublicTD[13]);
		TextDrawShowForPlayer(playerid, PublicTD[14]);
		TextDrawShowForPlayer(playerid, PublicTD[15]);
		TextDrawShowForPlayer(playerid, PublicTD[16]);
		TextDrawShowForPlayer(playerid, PublicTD[17]);
		TextDrawShowForPlayer(playerid, PublicTD[18]);
		TextDrawShowForPlayer(playerid, PublicTD[19]);
		TextDrawShowForPlayer(playerid, PublicTD[20]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][0]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][1]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][2]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][3]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][4]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][5]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][6]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][7]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][8]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][9]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][10]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][11]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][12]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][13]);
		SelectTextDraw(playerid, 0xFF0000FF);
		return 1;
	}
	return 0;
}
