/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

#include <a_samp>

new Text:PublicTD[16];
new PlayerText:PlayerTD[MAX_PLAYERS][9];

public OnFilterScriptInit()
{
	PublicTD[0] = TextDrawCreate(64.000000, 90.000000, "ld_dual:white");
	TextDrawFont(PublicTD[0], 4);
	TextDrawLetterSize(PublicTD[0], 0.600000, 2.000000);
	TextDrawTextSize(PublicTD[0], 512.000000, 270.000000);
	TextDrawSetOutline(PublicTD[0], 1);
	TextDrawSetShadow(PublicTD[0], 0);
	TextDrawAlignment(PublicTD[0], 1);
	TextDrawColor(PublicTD[0], 170);
	TextDrawBackgroundColor(PublicTD[0], 255);
	TextDrawBoxColor(PublicTD[0], 50);
	TextDrawUseBox(PublicTD[0], 1);
	TextDrawSetProportional(PublicTD[0], 1);
	TextDrawSetSelectable(PublicTD[0], 0);

	PublicTD[1] = TextDrawCreate(64.000000, 90.000000, "ld_dual:white");
	TextDrawFont(PublicTD[1], 4);
	TextDrawLetterSize(PublicTD[1], 0.600000, 2.000000);
	TextDrawTextSize(PublicTD[1], 512.000000, 30.000000);
	TextDrawSetOutline(PublicTD[1], 1);
	TextDrawSetShadow(PublicTD[1], 0);
	TextDrawAlignment(PublicTD[1], 1);
	TextDrawColor(PublicTD[1], -1439432705);
	TextDrawBackgroundColor(PublicTD[1], 255);
	TextDrawBoxColor(PublicTD[1], 50);
	TextDrawUseBox(PublicTD[1], 1);
	TextDrawSetProportional(PublicTD[1], 1);
	TextDrawSetSelectable(PublicTD[1], 0);

	PublicTD[2] = TextDrawCreate(320.000000, 90.000000, "GARAGEM");
	TextDrawFont(PublicTD[2], 2);
	TextDrawLetterSize(PublicTD[2], 0.500000, 3.000000);
	TextDrawTextSize(PublicTD[2], 400.000000, 17.000000);
	TextDrawSetOutline(PublicTD[2], 0);
	TextDrawSetShadow(PublicTD[2], 0);
	TextDrawAlignment(PublicTD[2], 2);
	TextDrawColor(PublicTD[2], -1);
	TextDrawBackgroundColor(PublicTD[2], 255);
	TextDrawBoxColor(PublicTD[2], 50);
	TextDrawUseBox(PublicTD[2], 0);
	TextDrawSetProportional(PublicTD[2], 1);
	TextDrawSetSelectable(PublicTD[2], 0);

	PublicTD[3] = TextDrawCreate(180.000000, 270.000000, "ld_dual:white");
	TextDrawFont(PublicTD[3], 4);
	TextDrawLetterSize(PublicTD[3], 0.600000, 2.000000);
	TextDrawTextSize(PublicTD[3], 280.000000, 17.000000);
	TextDrawSetOutline(PublicTD[3], 1);
	TextDrawSetShadow(PublicTD[3], 0);
	TextDrawAlignment(PublicTD[3], 1);
	TextDrawColor(PublicTD[3], -1962934017);
	TextDrawBackgroundColor(PublicTD[3], 255);
	TextDrawBoxColor(PublicTD[3], 50);
	TextDrawUseBox(PublicTD[3], 1);
	TextDrawSetProportional(PublicTD[3], 1);
	TextDrawSetSelectable(PublicTD[3], 0);

	PublicTD[4] = TextDrawCreate(180.000000, 300.000000, "ld_dual:white");
	TextDrawFont(PublicTD[4], 4);
	TextDrawLetterSize(PublicTD[4], 0.600000, 2.000000);
	TextDrawTextSize(PublicTD[4], 280.000000, 17.000000);
	TextDrawSetOutline(PublicTD[4], 1);
	TextDrawSetShadow(PublicTD[4], 0);
	TextDrawAlignment(PublicTD[4], 1);
	TextDrawColor(PublicTD[4], -1962934017);
	TextDrawBackgroundColor(PublicTD[4], 255);
	TextDrawBoxColor(PublicTD[4], 50);
	TextDrawUseBox(PublicTD[4], 1);
	TextDrawSetProportional(PublicTD[4], 1);
	TextDrawSetSelectable(PublicTD[4], 0);

	PublicTD[5] = TextDrawCreate(155.000000, 270.000000, "HUD:radar_girlfriend");
	TextDrawFont(PublicTD[5], 4);
	TextDrawLetterSize(PublicTD[5], 0.600000, 2.000000);
	TextDrawTextSize(PublicTD[5], 17.000000, 17.000000);
	TextDrawSetOutline(PublicTD[5], 1);
	TextDrawSetShadow(PublicTD[5], 0);
	TextDrawAlignment(PublicTD[5], 1);
	TextDrawColor(PublicTD[5], -1);
	TextDrawBackgroundColor(PublicTD[5], 255);
	TextDrawBoxColor(PublicTD[5], 50);
	TextDrawUseBox(PublicTD[5], 1);
	TextDrawSetProportional(PublicTD[5], 1);
	TextDrawSetSelectable(PublicTD[5], 0);

	PublicTD[6] = TextDrawCreate(155.000000, 300.000000, "HUD:radar_centre");
	TextDrawFont(PublicTD[6], 4);
	TextDrawLetterSize(PublicTD[6], 0.600000, 2.000000);
	TextDrawTextSize(PublicTD[6], 17.000000, 17.000000);
	TextDrawSetOutline(PublicTD[6], 1);
	TextDrawSetShadow(PublicTD[6], 0);
	TextDrawAlignment(PublicTD[6], 1);
	TextDrawColor(PublicTD[6], -1);
	TextDrawBackgroundColor(PublicTD[6], 255);
	TextDrawBoxColor(PublicTD[6], 50);
	TextDrawUseBox(PublicTD[6], 1);
	TextDrawSetProportional(PublicTD[6], 1);
	TextDrawSetSelectable(PublicTD[6], 0);

	PublicTD[7] = TextDrawCreate(155.000000, 330.000000, "HUD:radar_gym");
	TextDrawFont(PublicTD[7], 4);
	TextDrawLetterSize(PublicTD[7], 0.600000, 2.000000);
	TextDrawTextSize(PublicTD[7], 17.000000, 17.000000);
	TextDrawSetOutline(PublicTD[7], 1);
	TextDrawSetShadow(PublicTD[7], 0);
	TextDrawAlignment(PublicTD[7], 1);
	TextDrawColor(PublicTD[7], -1);
	TextDrawBackgroundColor(PublicTD[7], 255);
	TextDrawBoxColor(PublicTD[7], 50);
	TextDrawUseBox(PublicTD[7], 1);
	TextDrawSetProportional(PublicTD[7], 1);
	TextDrawSetSelectable(PublicTD[7], 0);

	PublicTD[8] = TextDrawCreate(180.000000, 330.000000, "ld_dual:white");
	TextDrawFont(PublicTD[8], 4);
	TextDrawLetterSize(PublicTD[8], 0.600000, 2.000000);
	TextDrawTextSize(PublicTD[8], 280.000000, 17.000000);
	TextDrawSetOutline(PublicTD[8], 1);
	TextDrawSetShadow(PublicTD[8], 0);
	TextDrawAlignment(PublicTD[8], 1);
	TextDrawColor(PublicTD[8], -1962934017);
	TextDrawBackgroundColor(PublicTD[8], 255);
	TextDrawBoxColor(PublicTD[8], 50);
	TextDrawUseBox(PublicTD[8], 1);
	TextDrawSetProportional(PublicTD[8], 1);
	TextDrawSetSelectable(PublicTD[8], 0);

	PublicTD[9] = TextDrawCreate(470.000000, 137.000000, "ld_dual:white");
	TextDrawFont(PublicTD[9], 4);
	TextDrawLetterSize(PublicTD[9], 0.600000, 2.000000);
	TextDrawTextSize(PublicTD[9], 95.000000, 45.000000);
	TextDrawSetOutline(PublicTD[9], 1);
	TextDrawSetShadow(PublicTD[9], 0);
	TextDrawAlignment(PublicTD[9], 1);
	TextDrawColor(PublicTD[9], -1439432705);
	TextDrawBackgroundColor(PublicTD[9], 255);
	TextDrawBoxColor(PublicTD[9], 50);
	TextDrawUseBox(PublicTD[9], 1);
	TextDrawSetProportional(PublicTD[9], 1);
	TextDrawSetSelectable(PublicTD[9], 1);

	PublicTD[10] = TextDrawCreate(517.500000, 147.500000, "GUARDAR");
	TextDrawFont(PublicTD[10], 2);
	TextDrawLetterSize(PublicTD[10], 0.400000, 2.400000);
	TextDrawTextSize(PublicTD[10], 400.000000, 17.000000);
	TextDrawSetOutline(PublicTD[10], 0);
	TextDrawSetShadow(PublicTD[10], 0);
	TextDrawAlignment(PublicTD[10], 2);
	TextDrawColor(PublicTD[10], -1);
	TextDrawBackgroundColor(PublicTD[10], 255);
	TextDrawBoxColor(PublicTD[10], 50);
	TextDrawUseBox(PublicTD[10], 0);
	TextDrawSetProportional(PublicTD[10], 1);
	TextDrawSetSelectable(PublicTD[10], 0);

	PublicTD[11] = TextDrawCreate(155.500000, 240.500000, "~p~VEICULO: ~w~<VEHICLE_NAME>");
	TextDrawFont(PublicTD[11], 2);
	TextDrawLetterSize(PublicTD[11], 0.300000, 1.799999);
	TextDrawTextSize(PublicTD[11], 457.000000, 547.500000);
	TextDrawSetOutline(PublicTD[11], 0);
	TextDrawSetShadow(PublicTD[11], 0);
	TextDrawAlignment(PublicTD[11], 1);
	TextDrawColor(PublicTD[11], -1);
	TextDrawBackgroundColor(PublicTD[11], 255);
	TextDrawBoxColor(PublicTD[11], 50);
	TextDrawUseBox(PublicTD[11], 0);
	TextDrawSetProportional(PublicTD[11], 1);
	TextDrawSetSelectable(PublicTD[11], 0);

	PublicTD[12] = TextDrawCreate(470.000000, 302.500000, "ld_dual:white");
	TextDrawFont(PublicTD[12], 4);
	TextDrawLetterSize(PublicTD[12], 0.600000, 2.000000);
	TextDrawTextSize(PublicTD[12], 95.000000, 45.000000);
	TextDrawSetOutline(PublicTD[12], 1);
	TextDrawSetShadow(PublicTD[12], 0);
	TextDrawAlignment(PublicTD[12], 1);
	TextDrawColor(PublicTD[12], -13421569);
	TextDrawBackgroundColor(PublicTD[12], 255);
	TextDrawBoxColor(PublicTD[12], 50);
	TextDrawUseBox(PublicTD[12], 1);
	TextDrawSetProportional(PublicTD[12], 1);
	TextDrawSetSelectable(PublicTD[12], 1);

	PublicTD[13] = TextDrawCreate(517.500000, 313.500000, "FECHAR");
	TextDrawFont(PublicTD[13], 2);
	TextDrawLetterSize(PublicTD[13], 0.400000, 2.400000);
	TextDrawTextSize(PublicTD[13], 400.000000, 17.000000);
	TextDrawSetOutline(PublicTD[13], 0);
	TextDrawSetShadow(PublicTD[13], 0);
	TextDrawAlignment(PublicTD[13], 2);
	TextDrawColor(PublicTD[13], -1);
	TextDrawBackgroundColor(PublicTD[13], 255);
	TextDrawBoxColor(PublicTD[13], 50);
	TextDrawUseBox(PublicTD[13], 0);
	TextDrawSetProportional(PublicTD[13], 1);
	TextDrawSetSelectable(PublicTD[13], 0);

	PublicTD[14] = TextDrawCreate(470.000000, 217.500000, "ld_dual:white");
	TextDrawFont(PublicTD[14], 4);
	TextDrawLetterSize(PublicTD[14], 0.600000, 2.000000);
	TextDrawTextSize(PublicTD[14], 95.000000, 45.000000);
	TextDrawSetOutline(PublicTD[14], 1);
	TextDrawSetShadow(PublicTD[14], 0);
	TextDrawAlignment(PublicTD[14], 1);
	TextDrawColor(PublicTD[14], 1097458175);
	TextDrawBackgroundColor(PublicTD[14], 255);
	TextDrawBoxColor(PublicTD[14], 50);
	TextDrawUseBox(PublicTD[14], 1);
	TextDrawSetProportional(PublicTD[14], 1);
	TextDrawSetSelectable(PublicTD[14], 1);

	PublicTD[15] = TextDrawCreate(517.500000, 227.500000, "retirar");
	TextDrawFont(PublicTD[15], 2);
	TextDrawLetterSize(PublicTD[15], 0.400000, 2.400000);
	TextDrawTextSize(PublicTD[15], 400.000000, 17.000000);
	TextDrawSetOutline(PublicTD[15], 0);
	TextDrawSetShadow(PublicTD[15], 0);
	TextDrawAlignment(PublicTD[15], 2);
	TextDrawColor(PublicTD[15], -1);
	TextDrawBackgroundColor(PublicTD[15], 255);
	TextDrawBoxColor(PublicTD[15], 50);
	TextDrawUseBox(PublicTD[15], 0);
	TextDrawSetProportional(PublicTD[15], 1);
	TextDrawSetSelectable(PublicTD[15], 0);

	return 1;
}

public OnFilterScriptExit()
{
	TextDrawDestroy(PublicTD[0]);
	TextDrawDestroy(PublicTD[1]);
	TextDrawDestroy(PublicTD[2]);
	TextDrawDestroy(PublicTD[3]);
	TextDrawDestroy(PublicTD[4]);
	TextDrawDestroy(PublicTD[5]);
	TextDrawDestroy(PublicTD[6]);
	TextDrawDestroy(PublicTD[7]);
	TextDrawDestroy(PublicTD[8]);
	TextDrawDestroy(PublicTD[9]);
	TextDrawDestroy(PublicTD[10]);
	TextDrawDestroy(PublicTD[11]);
	TextDrawDestroy(PublicTD[12]);
	TextDrawDestroy(PublicTD[13]);
	TextDrawDestroy(PublicTD[14]);
	TextDrawDestroy(PublicTD[15]);
	return 1;
}

public OnPlayerConnect(playerid)
{
	PlayerTD[playerid][0] = CreatePlayerTextDraw(playerid, 64.000000, 120.000000, "Preview_Model");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][0], 5);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][0], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][0], 80.000000, 80.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][0], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][0], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][0], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][0], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][0], 125);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][0], 255);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][0], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][0], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][0], 1);
	PlayerTextDrawSetPreviewModel(playerid, PlayerTD[playerid][0], 411);
	PlayerTextDrawSetPreviewRot(playerid, PlayerTD[playerid][0], -15.000000, 0.000000, -35.000000, 1.000000);
	PlayerTextDrawSetPreviewVehCol(playerid, PlayerTD[playerid][0], 1, 1);

	PlayerTD[playerid][1] = CreatePlayerTextDraw(playerid, 64.000000, 200.000000, "Preview_Model");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][1], 5);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][1], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][1], 80.000000, 80.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][1], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][1], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][1], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][1], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][1], 125);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][1], 255);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][1], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][1], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][1], 1);
	PlayerTextDrawSetPreviewModel(playerid, PlayerTD[playerid][1], 411);
	PlayerTextDrawSetPreviewRot(playerid, PlayerTD[playerid][1], -15.000000, 0.000000, -35.000000, 1.000000);
	PlayerTextDrawSetPreviewVehCol(playerid, PlayerTD[playerid][1], 9, 12);

	PlayerTD[playerid][2] = CreatePlayerTextDraw(playerid, 64.000000, 280.000000, "Preview_Model");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][2], 5);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][2], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][2], 80.000000, 80.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][2], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][2], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][2], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][2], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][2], 125);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][2], 255);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][2], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][2], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][2], 1);
	PlayerTextDrawSetPreviewModel(playerid, PlayerTD[playerid][2], 411);
	PlayerTextDrawSetPreviewRot(playerid, PlayerTD[playerid][2], -15.000000, 0.000000, -35.000000, 1.000000);
	PlayerTextDrawSetPreviewVehCol(playerid, PlayerTD[playerid][2], 1, 1);

	PlayerTD[playerid][3] = CreatePlayerTextDraw(playerid, 230.000000, 75.000000, "Preview_Model");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][3], 5);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][3], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][3], 180.000000, 200.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][3], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][3], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][3], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][3], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][3], 0);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][3], 255);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][3], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][3], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][3], 0);
	PlayerTextDrawSetPreviewModel(playerid, PlayerTD[playerid][3], 411);
	PlayerTextDrawSetPreviewRot(playerid, PlayerTD[playerid][3], -5.000000, 0.000000, -55.000000, 1.000000);
	PlayerTextDrawSetPreviewVehCol(playerid, PlayerTD[playerid][3], 9, 12);

	PlayerTD[playerid][4] = CreatePlayerTextDraw(playerid, 180.000000, 270.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][4], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][4], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][4], 140.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][4], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][4], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][4], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][4], 16711935);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][4], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][4], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][4], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][4], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][4], 0);

	PlayerTD[playerid][5] = CreatePlayerTextDraw(playerid, 180.000000, 300.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][5], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][5], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][5], 140.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][5], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][5], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][5], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][5], 16711935);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][5], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][5], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][5], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][5], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][5], 0);

	PlayerTD[playerid][6] = CreatePlayerTextDraw(playerid, 180.000000, 330.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][6], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][6], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][6], 140.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][6], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][6], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][6], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][6], 16711935);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][6], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][6], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][6], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][6], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][6], 0);

	PlayerTD[playerid][7] = CreatePlayerTextDraw(playerid, 391.000000, 186.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][7], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][7], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][7], 20.000000, 20.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][7], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][7], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][7], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][7], -1439432705);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][7], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][7], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][7], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][7], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][7], 0);

	PlayerTD[playerid][8] = CreatePlayerTextDraw(playerid, 391.000000, 142.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][8], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][8], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][8], 20.000000, 20.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][8], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][8], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][8], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][8], -1439432705);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][8], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][8], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][8], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][8], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][8], 0);

	return 1;
}

public OnPlayerDisconnect(playerid, reason)
{
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][0]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][1]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][2]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][3]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][4]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][5]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][6]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][7]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][8]);
	return 1;
}

public OnPlayerCommandText(playerid, cmdtext[])
{
	if(!strcmp(cmdtext, "/tdtest", true))
	{
		TextDrawShowForPlayer(playerid, PublicTD[0]);
		TextDrawShowForPlayer(playerid, PublicTD[1]);
		TextDrawShowForPlayer(playerid, PublicTD[2]);
		TextDrawShowForPlayer(playerid, PublicTD[3]);
		TextDrawShowForPlayer(playerid, PublicTD[4]);
		TextDrawShowForPlayer(playerid, PublicTD[5]);
		TextDrawShowForPlayer(playerid, PublicTD[6]);
		TextDrawShowForPlayer(playerid, PublicTD[7]);
		TextDrawShowForPlayer(playerid, PublicTD[8]);
		TextDrawShowForPlayer(playerid, PublicTD[9]);
		TextDrawShowForPlayer(playerid, PublicTD[10]);
		TextDrawShowForPlayer(playerid, PublicTD[11]);
		TextDrawShowForPlayer(playerid, PublicTD[12]);
		TextDrawShowForPlayer(playerid, PublicTD[13]);
		TextDrawShowForPlayer(playerid, PublicTD[14]);
		TextDrawShowForPlayer(playerid, PublicTD[15]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][0]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][1]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][2]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][3]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][4]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][5]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][6]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][7]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][8]);
		SelectTextDraw(playerid, 0xFF0000FF);
		return 1;
	}
	return 0;
}
