/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

#include <a_samp>

new Text:PublicTD[13];
new PlayerText:PlayerTD[MAX_PLAYERS][5];

public OnFilterScriptInit()
{
	PublicTD[0] = TextDrawCreate(341.000000, 414.500000, "ld_beat:chit");
	TextDrawFont(PublicTD[0], 4);
	TextDrawLetterSize(PublicTD[0], 0.600000, 2.000000);
	TextDrawTextSize(PublicTD[0], 33.000000, 33.000000);
	TextDrawSetOutline(PublicTD[0], 1);
	TextDrawSetShadow(PublicTD[0], 0);
	TextDrawAlignment(PublicTD[0], 1);
	TextDrawColor(PublicTD[0], 872363007);
	TextDrawBackgroundColor(PublicTD[0], 255);
	TextDrawBoxColor(PublicTD[0], 50);
	TextDrawUseBox(PublicTD[0], 1);
	TextDrawSetProportional(PublicTD[0], 1);
	TextDrawSetSelectable(PublicTD[0], 0);

	PublicTD[1] = TextDrawCreate(265.000000, 414.500000, "ld_beat:chit");
	TextDrawFont(PublicTD[1], 4);
	TextDrawLetterSize(PublicTD[1], 0.600000, 2.000000);
	TextDrawTextSize(PublicTD[1], 33.000000, 33.000000);
	TextDrawSetOutline(PublicTD[1], 1);
	TextDrawSetShadow(PublicTD[1], 0);
	TextDrawAlignment(PublicTD[1], 1);
	TextDrawColor(PublicTD[1], 872363007);
	TextDrawBackgroundColor(PublicTD[1], 255);
	TextDrawBoxColor(PublicTD[1], 50);
	TextDrawUseBox(PublicTD[1], 1);
	TextDrawSetProportional(PublicTD[1], 1);
	TextDrawSetSelectable(PublicTD[1], 0);

	PublicTD[2] = TextDrawCreate(0.000000, 430.000000, "ld_dual:white");
	TextDrawFont(PublicTD[2], 4);
	TextDrawLetterSize(PublicTD[2], 0.600000, 2.000000);
	TextDrawTextSize(PublicTD[2], 640.000000, 18.000000);
	TextDrawSetOutline(PublicTD[2], 1);
	TextDrawSetShadow(PublicTD[2], 0);
	TextDrawAlignment(PublicTD[2], 1);
	TextDrawColor(PublicTD[2], 872363007);
	TextDrawBackgroundColor(PublicTD[2], 255);
	TextDrawBoxColor(PublicTD[2], 50);
	TextDrawUseBox(PublicTD[2], 1);
	TextDrawSetProportional(PublicTD[2], 1);
	TextDrawSetSelectable(PublicTD[2], 0);

	PublicTD[3] = TextDrawCreate(0.000000, 433.000000, "ld_dual:white");
	TextDrawFont(PublicTD[3], 4);
	TextDrawLetterSize(PublicTD[3], 0.600000, 2.000000);
	TextDrawTextSize(PublicTD[3], 640.000000, 18.000000);
	TextDrawSetOutline(PublicTD[3], 1);
	TextDrawSetShadow(PublicTD[3], 0);
	TextDrawAlignment(PublicTD[3], 1);
	TextDrawColor(PublicTD[3], 255);
	TextDrawBackgroundColor(PublicTD[3], 255);
	TextDrawBoxColor(PublicTD[3], 50);
	TextDrawUseBox(PublicTD[3], 1);
	TextDrawSetProportional(PublicTD[3], 1);
	TextDrawSetSelectable(PublicTD[3], 0);

	PublicTD[4] = TextDrawCreate(565.000000, 433.000000, "00:00~n~12_de_fevereiro_de_2026");
	TextDrawFont(PublicTD[4], 2);
	TextDrawLetterSize(PublicTD[4], 0.187500, 0.750000);
	TextDrawTextSize(PublicTD[4], 400.000000, 170.500000);
	TextDrawSetOutline(PublicTD[4], 0);
	TextDrawSetShadow(PublicTD[4], 0);
	TextDrawAlignment(PublicTD[4], 2);
	TextDrawColor(PublicTD[4], 1157580031);
	TextDrawBackgroundColor(PublicTD[4], 255);
	TextDrawBoxColor(PublicTD[4], 50);
	TextDrawUseBox(PublicTD[4], 0);
	TextDrawSetProportional(PublicTD[4], 1);
	TextDrawSetSelectable(PublicTD[4], 0);

	PublicTD[5] = TextDrawCreate(280.000000, 419.950012, "ld_dual:white");
	TextDrawFont(PublicTD[5], 4);
	TextDrawLetterSize(PublicTD[5], 0.600000, 2.000000);
	TextDrawTextSize(PublicTD[5], 80.000000, 19.500000);
	TextDrawSetOutline(PublicTD[5], 1);
	TextDrawSetShadow(PublicTD[5], 0);
	TextDrawAlignment(PublicTD[5], 1);
	TextDrawColor(PublicTD[5], 872363007);
	TextDrawBackgroundColor(PublicTD[5], 255);
	TextDrawBoxColor(PublicTD[5], 50);
	TextDrawUseBox(PublicTD[5], 1);
	TextDrawSetProportional(PublicTD[5], 1);
	TextDrawSetSelectable(PublicTD[5], 0);

	PublicTD[6] = TextDrawCreate(267.000000, 416.500000, "ld_beat:chit");
	TextDrawFont(PublicTD[6], 4);
	TextDrawLetterSize(PublicTD[6], 0.600000, 2.000000);
	TextDrawTextSize(PublicTD[6], 33.000000, 33.000000);
	TextDrawSetOutline(PublicTD[6], 1);
	TextDrawSetShadow(PublicTD[6], 0);
	TextDrawAlignment(PublicTD[6], 1);
	TextDrawColor(PublicTD[6], 255);
	TextDrawBackgroundColor(PublicTD[6], 255);
	TextDrawBoxColor(PublicTD[6], 50);
	TextDrawUseBox(PublicTD[6], 1);
	TextDrawSetProportional(PublicTD[6], 1);
	TextDrawSetSelectable(PublicTD[6], 0);

	PublicTD[7] = TextDrawCreate(283.000000, 422.000000, "ld_dual:white");
	TextDrawFont(PublicTD[7], 4);
	TextDrawLetterSize(PublicTD[7], 0.600000, 2.000000);
	TextDrawTextSize(PublicTD[7], 74.000000, 19.500000);
	TextDrawSetOutline(PublicTD[7], 1);
	TextDrawSetShadow(PublicTD[7], 0);
	TextDrawAlignment(PublicTD[7], 1);
	TextDrawColor(PublicTD[7], 255);
	TextDrawBackgroundColor(PublicTD[7], 255);
	TextDrawBoxColor(PublicTD[7], 50);
	TextDrawUseBox(PublicTD[7], 1);
	TextDrawSetProportional(PublicTD[7], 1);
	TextDrawSetSelectable(PublicTD[7], 0);

	PublicTD[8] = TextDrawCreate(339.000000, 416.500000, "ld_beat:chit");
	TextDrawFont(PublicTD[8], 4);
	TextDrawLetterSize(PublicTD[8], 0.600000, 2.000000);
	TextDrawTextSize(PublicTD[8], 33.000000, 33.000000);
	TextDrawSetOutline(PublicTD[8], 1);
	TextDrawSetShadow(PublicTD[8], 0);
	TextDrawAlignment(PublicTD[8], 1);
	TextDrawColor(PublicTD[8], 255);
	TextDrawBackgroundColor(PublicTD[8], 255);
	TextDrawBoxColor(PublicTD[8], 50);
	TextDrawUseBox(PublicTD[8], 1);
	TextDrawSetProportional(PublicTD[8], 1);
	TextDrawSetSelectable(PublicTD[8], 0);

	PublicTD[9] = TextDrawCreate(320.000000, 426.000000, "BRASIL PLAY");
	TextDrawFont(PublicTD[9], 2);
	TextDrawLetterSize(PublicTD[9], 0.250000, 1.000000);
	TextDrawTextSize(PublicTD[9], 400.000000, 121.000000);
	TextDrawSetOutline(PublicTD[9], 0);
	TextDrawSetShadow(PublicTD[9], 0);
	TextDrawAlignment(PublicTD[9], 2);
	TextDrawColor(PublicTD[9], -1);
	TextDrawBackgroundColor(PublicTD[9], 255);
	TextDrawBoxColor(PublicTD[9], 50);
	TextDrawUseBox(PublicTD[9], 0);
	TextDrawSetProportional(PublicTD[9], 1);
	TextDrawSetSelectable(PublicTD[9], 0);

	PublicTD[10] = TextDrawCreate(333.750000, 435.649993, "t");
	TextDrawFont(PublicTD[10], 2);
	TextDrawLetterSize(PublicTD[10], 0.300000, 1.200000);
	TextDrawTextSize(PublicTD[10], 400.000000, 17.000000);
	TextDrawSetOutline(PublicTD[10], 0);
	TextDrawSetShadow(PublicTD[10], 0);
	TextDrawAlignment(PublicTD[10], 2);
	TextDrawColor(PublicTD[10], 872363007);
	TextDrawBackgroundColor(PublicTD[10], 255);
	TextDrawBoxColor(PublicTD[10], 50);
	TextDrawUseBox(PublicTD[10], 0);
	TextDrawSetProportional(PublicTD[10], 1);
	TextDrawSetSelectable(PublicTD[10], 0);

	PublicTD[11] = TextDrawCreate(320.000000, 439.000000, "tree");
	TextDrawFont(PublicTD[11], 2);
	TextDrawLetterSize(PublicTD[11], 0.200000, 0.800000);
	TextDrawTextSize(PublicTD[11], 400.000000, 17.000000);
	TextDrawSetOutline(PublicTD[11], 0);
	TextDrawSetShadow(PublicTD[11], 0);
	TextDrawAlignment(PublicTD[11], 2);
	TextDrawColor(PublicTD[11], -1);
	TextDrawBackgroundColor(PublicTD[11], 255);
	TextDrawBoxColor(PublicTD[11], 50);
	TextDrawUseBox(PublicTD[11], 0);
	TextDrawSetProportional(PublicTD[11], 1);
	TextDrawSetSelectable(PublicTD[11], 0);

	PublicTD[12] = TextDrawCreate(305.850006, 435.649993, "S");
	TextDrawFont(PublicTD[12], 2);
	TextDrawLetterSize(PublicTD[12], 0.300000, 1.200000);
	TextDrawTextSize(PublicTD[12], 400.000000, 17.000000);
	TextDrawSetOutline(PublicTD[12], 0);
	TextDrawSetShadow(PublicTD[12], 0);
	TextDrawAlignment(PublicTD[12], 2);
	TextDrawColor(PublicTD[12], 872363007);
	TextDrawBackgroundColor(PublicTD[12], 255);
	TextDrawBoxColor(PublicTD[12], 50);
	TextDrawUseBox(PublicTD[12], 0);
	TextDrawSetProportional(PublicTD[12], 1);
	TextDrawSetSelectable(PublicTD[12], 0);

	return 1;
}

public OnFilterScriptExit()
{
	TextDrawDestroy(PublicTD[0]);
	TextDrawDestroy(PublicTD[1]);
	TextDrawDestroy(PublicTD[2]);
	TextDrawDestroy(PublicTD[3]);
	TextDrawDestroy(PublicTD[4]);
	TextDrawDestroy(PublicTD[5]);
	TextDrawDestroy(PublicTD[6]);
	TextDrawDestroy(PublicTD[7]);
	TextDrawDestroy(PublicTD[8]);
	TextDrawDestroy(PublicTD[9]);
	TextDrawDestroy(PublicTD[10]);
	TextDrawDestroy(PublicTD[11]);
	TextDrawDestroy(PublicTD[12]);
	return 1;
}

public OnPlayerConnect(playerid)
{
	PlayerTD[playerid][0] = CreatePlayerTextDraw(playerid, 45.000000, 437.500000, "CPF: 999");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][0], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][0], 0.281250, 1.125000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][0], 400.000000, 170.500000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][0], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][0], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][0], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][0], 1157580031);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][0], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][0], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][0], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][0], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][0], 0);

	PlayerTD[playerid][1] = CreatePlayerTextDraw(playerid, 463.333007, 437.500000, "~b~~h~~h~PAYDAY~w~ 00:00");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][1], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][1], 0.250000, 1.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][1], 400.000000, 170.500000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][1], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][1], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][1], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][1], 1157580031);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][1], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][1], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][1], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][1], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][1], 0);

	PlayerTD[playerid][2] = CreatePlayerTextDraw(playerid, 228.300003, 437.500000, "~g~~h~~h~R$: 999.999");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][2], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][2], 0.281250, 1.125000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][2], 400.000000, 170.500000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][2], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][2], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][2], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][2], 1157580031);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][2], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][2], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][2], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][2], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][2], 0);

	PlayerTD[playerid][3] = CreatePlayerTextDraw(playerid, 391.660003, 437.500000, "L: 999");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][3], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][3], 0.250000, 1.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][3], 400.000000, 170.500000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][3], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][3], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][3], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][3], 1157580031);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][3], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][3], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][3], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][3], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][3], 0);

	PlayerTD[playerid][4] = CreatePlayerTextDraw(playerid, 134.600006, 437.500000, "~y~B$: 999.999");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][4], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][4], 0.281250, 1.125000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][4], 400.000000, 170.500000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][4], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][4], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][4], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][4], 1157580031);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][4], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][4], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][4], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][4], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][4], 0);

	return 1;
}

public OnPlayerDisconnect(playerid, reason)
{
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][0]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][1]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][2]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][3]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][4]);
	return 1;
}

public OnPlayerCommandText(playerid, cmdtext[])
{
	if(!strcmp(cmdtext, "/tdtest", true))
	{
		TextDrawShowForPlayer(playerid, PublicTD[0]);
		TextDrawShowForPlayer(playerid, PublicTD[1]);
		TextDrawShowForPlayer(playerid, PublicTD[2]);
		TextDrawShowForPlayer(playerid, PublicTD[3]);
		TextDrawShowForPlayer(playerid, PublicTD[4]);
		TextDrawShowForPlayer(playerid, PublicTD[5]);
		TextDrawShowForPlayer(playerid, PublicTD[6]);
		TextDrawShowForPlayer(playerid, PublicTD[7]);
		TextDrawShowForPlayer(playerid, PublicTD[8]);
		TextDrawShowForPlayer(playerid, PublicTD[9]);
		TextDrawShowForPlayer(playerid, PublicTD[10]);
		TextDrawShowForPlayer(playerid, PublicTD[11]);
		TextDrawShowForPlayer(playerid, PublicTD[12]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][0]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][1]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][2]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][3]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][4]);
		return 1;
	}
	return 0;
}
