/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

#include <a_samp>

new Text:PublicTD[7];
new PlayerText:PlayerTD[MAX_PLAYERS][3];

public OnFilterScriptInit()
{
	PublicTD[0] = TextDrawCreate(220.000000, 100.000000, "ld_dual:white");
	TextDrawFont(PublicTD[0], 4);
	TextDrawLetterSize(PublicTD[0], 0.600000, 2.000000);
	TextDrawTextSize(PublicTD[0], 200.000000, 276.000000);
	TextDrawSetOutline(PublicTD[0], 1);
	TextDrawSetShadow(PublicTD[0], 0);
	TextDrawAlignment(PublicTD[0], 1);
	TextDrawColor(PublicTD[0], 170);
	TextDrawBackgroundColor(PublicTD[0], 255);
	TextDrawBoxColor(PublicTD[0], 50);
	TextDrawUseBox(PublicTD[0], 1);
	TextDrawSetProportional(PublicTD[0], 1);
	TextDrawSetSelectable(PublicTD[0], 0);

	PublicTD[1] = TextDrawCreate(320.000000, 154.500000, "~g~~h~~h~Brasil ~w~Player ~g~~h~~h~Street~n~~n~~g~~h~Digite uma senha:");
	TextDrawFont(PublicTD[1], 2);
	TextDrawLetterSize(PublicTD[1], 0.300000, 1.600000);
	TextDrawTextSize(PublicTD[1], 298.500000, 187.500000);
	TextDrawSetOutline(PublicTD[1], 0);
	TextDrawSetShadow(PublicTD[1], 0);
	TextDrawAlignment(PublicTD[1], 2);
	TextDrawColor(PublicTD[1], -1);
	TextDrawBackgroundColor(PublicTD[1], 255);
	TextDrawBoxColor(PublicTD[1], 135);
	TextDrawUseBox(PublicTD[1], 0);
	TextDrawSetProportional(PublicTD[1], 1);
	TextDrawSetSelectable(PublicTD[1], 0);

	PublicTD[2] = TextDrawCreate(220.000000, 100.000000, "ld_dual:white");
	TextDrawFont(PublicTD[2], 4);
	TextDrawLetterSize(PublicTD[2], 0.600000, 2.000000);
	TextDrawTextSize(PublicTD[2], 200.000000, 35.000000);
	TextDrawSetOutline(PublicTD[2], 1);
	TextDrawSetShadow(PublicTD[2], 0);
	TextDrawAlignment(PublicTD[2], 2);
	TextDrawColor(PublicTD[2], 872363007);
	TextDrawBackgroundColor(PublicTD[2], 255);
	TextDrawBoxColor(PublicTD[2], 50);
	TextDrawUseBox(PublicTD[2], 1);
	TextDrawSetProportional(PublicTD[2], 1);
	TextDrawSetSelectable(PublicTD[2], 0);

	PublicTD[3] = TextDrawCreate(230.000000, 217.000000, "USUARIO:");
	TextDrawFont(PublicTD[3], 2);
	TextDrawLetterSize(PublicTD[3], 0.300000, 1.600000);
	TextDrawTextSize(PublicTD[3], 298.500000, 184.500000);
	TextDrawSetOutline(PublicTD[3], 0);
	TextDrawSetShadow(PublicTD[3], 0);
	TextDrawAlignment(PublicTD[3], 1);
	TextDrawColor(PublicTD[3], -1);
	TextDrawBackgroundColor(PublicTD[3], 255);
	TextDrawBoxColor(PublicTD[3], 135);
	TextDrawUseBox(PublicTD[3], 0);
	TextDrawSetProportional(PublicTD[3], 1);
	TextDrawSetSelectable(PublicTD[3], 0);

	PublicTD[4] = TextDrawCreate(230.000000, 286.000000, "SENHA:");
	TextDrawFont(PublicTD[4], 2);
	TextDrawLetterSize(PublicTD[4], 0.300000, 1.600000);
	TextDrawTextSize(PublicTD[4], 298.500000, 184.500000);
	TextDrawSetOutline(PublicTD[4], 0);
	TextDrawSetShadow(PublicTD[4], 0);
	TextDrawAlignment(PublicTD[4], 1);
	TextDrawColor(PublicTD[4], -1);
	TextDrawBackgroundColor(PublicTD[4], 255);
	TextDrawBoxColor(PublicTD[4], 135);
	TextDrawUseBox(PublicTD[4], 0);
	TextDrawSetProportional(PublicTD[4], 1);
	TextDrawSetSelectable(PublicTD[4], 0);

	PublicTD[5] = TextDrawCreate(230.000000, 302.000000, "ld_dual:white");
	TextDrawFont(PublicTD[5], 4);
	TextDrawLetterSize(PublicTD[5], 0.600000, 2.000000);
	TextDrawTextSize(PublicTD[5], 180.000000, 35.000000);
	TextDrawSetOutline(PublicTD[5], 1);
	TextDrawSetShadow(PublicTD[5], 0);
	TextDrawAlignment(PublicTD[5], 2);
	TextDrawColor(PublicTD[5], 867906559);
	TextDrawBackgroundColor(PublicTD[5], 255);
	TextDrawBoxColor(PublicTD[5], 50);
	TextDrawUseBox(PublicTD[5], 1);
	TextDrawSetProportional(PublicTD[5], 1);
	TextDrawSetSelectable(PublicTD[5], 1);

	PublicTD[6] = TextDrawCreate(230.000000, 234.000000, "ld_dual:white");
	TextDrawFont(PublicTD[6], 4);
	TextDrawLetterSize(PublicTD[6], 0.600000, 2.000000);
	TextDrawTextSize(PublicTD[6], 180.000000, 35.000000);
	TextDrawSetOutline(PublicTD[6], 1);
	TextDrawSetShadow(PublicTD[6], 0);
	TextDrawAlignment(PublicTD[6], 2);
	TextDrawColor(PublicTD[6], 867906559);
	TextDrawBackgroundColor(PublicTD[6], 255);
	TextDrawBoxColor(PublicTD[6], 50);
	TextDrawUseBox(PublicTD[6], 1);
	TextDrawSetProportional(PublicTD[6], 1);
	TextDrawSetSelectable(PublicTD[6], 0);

	return 1;
}

public OnFilterScriptExit()
{
	TextDrawDestroy(PublicTD[0]);
	TextDrawDestroy(PublicTD[1]);
	TextDrawDestroy(PublicTD[2]);
	TextDrawDestroy(PublicTD[3]);
	TextDrawDestroy(PublicTD[4]);
	TextDrawDestroy(PublicTD[5]);
	TextDrawDestroy(PublicTD[6]);
	return 1;
}

public OnPlayerConnect(playerid)
{
	PlayerTD[playerid][0] = CreatePlayerTextDraw(playerid, 320.000000, 107.000000, "<TITLE>");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][0], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][0], 0.449999, 2.400000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][0], 298.500000, 75.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][0], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][0], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][0], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][0], 255);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][0], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][0], 135);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][0], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][0], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][0], 0);

	PlayerTD[playerid][1] = CreatePlayerTextDraw(playerid, 235.000000, 242.000000, "<PLAYER_NAME>");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][1], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][1], 0.300000, 1.600000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][1], 298.500000, 184.500000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][1], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][1], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][1], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][1], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][1], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][1], 135);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][1], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][1], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][1], 0);

	PlayerTD[playerid][2] = CreatePlayerTextDraw(playerid, 235.000000, 312.000000, "DIGITE_SUA_SENHA");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][2], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][2], 0.300000, 1.600000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][2], 298.500000, 184.500000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][2], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][2], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][2], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][2], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][2], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][2], 135);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][2], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][2], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][2], 0);

	return 1;
}

public OnPlayerDisconnect(playerid, reason)
{
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][0]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][1]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][2]);
	return 1;
}

public OnPlayerCommandText(playerid, cmdtext[])
{
	if(!strcmp(cmdtext, "/tdtest", true))
	{
		TextDrawShowForPlayer(playerid, PublicTD[0]);
		TextDrawShowForPlayer(playerid, PublicTD[1]);
		TextDrawShowForPlayer(playerid, PublicTD[2]);
		TextDrawShowForPlayer(playerid, PublicTD[3]);
		TextDrawShowForPlayer(playerid, PublicTD[4]);
		TextDrawShowForPlayer(playerid, PublicTD[5]);
		TextDrawShowForPlayer(playerid, PublicTD[6]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][0]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][1]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][2]);
		SelectTextDraw(playerid, 0xFF0000FF);
		return 1;
	}
	return 0;
}
