/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

#include <a_samp>

new Text:PublicTD[18];
new PlayerText:PlayerTD[MAX_PLAYERS][3];

public OnFilterScriptInit()
{
	PublicTD[0] = TextDrawCreate(0.000000, 0.000000, "_");
	TextDrawFont(PublicTD[0], 1);
	TextDrawLetterSize(PublicTD[0], 0.000000, 50.000000);
	TextDrawTextSize(PublicTD[0], 650.000000, 100.000000);
	TextDrawSetOutline(PublicTD[0], 1);
	TextDrawSetShadow(PublicTD[0], 4);
	TextDrawAlignment(PublicTD[0], 1);
	TextDrawColor(PublicTD[0], -1);
	TextDrawBackgroundColor(PublicTD[0], 255);
	TextDrawBoxColor(PublicTD[0], 1583243007);
	TextDrawUseBox(PublicTD[0], 1);
	TextDrawSetProportional(PublicTD[0], 1);
	TextDrawSetSelectable(PublicTD[0], 0);

	PublicTD[1] = TextDrawCreate(50.000000, 104.000000, "LOGIN");
	TextDrawFont(PublicTD[1], 2);
	TextDrawLetterSize(PublicTD[1], 0.429165, 1.899999);
	TextDrawTextSize(PublicTD[1], 118.000000, 23.000000);
	TextDrawSetOutline(PublicTD[1], 0);
	TextDrawSetShadow(PublicTD[1], 1);
	TextDrawAlignment(PublicTD[1], 1);
	TextDrawColor(PublicTD[1], -1);
	TextDrawBackgroundColor(PublicTD[1], 255);
	TextDrawBoxColor(PublicTD[1], 50);
	TextDrawUseBox(PublicTD[1], 0);
	TextDrawSetProportional(PublicTD[1], 1);
	TextDrawSetSelectable(PublicTD[1], 0);

	PublicTD[2] = TextDrawCreate(52.000000, 117.000000, "BPS");
	TextDrawFont(PublicTD[2], 2);
	TextDrawLetterSize(PublicTD[2], 0.916665, 5.400002);
	TextDrawTextSize(PublicTD[2], 400.000000, 17.000000);
	TextDrawSetOutline(PublicTD[2], 0);
	TextDrawSetShadow(PublicTD[2], 0);
	TextDrawAlignment(PublicTD[2], 1);
	TextDrawColor(PublicTD[2], 255);
	TextDrawBackgroundColor(PublicTD[2], 255);
	TextDrawBoxColor(PublicTD[2], 50);
	TextDrawUseBox(PublicTD[2], 0);
	TextDrawSetProportional(PublicTD[2], 1);
	TextDrawSetSelectable(PublicTD[2], 0);

	PublicTD[3] = TextDrawCreate(49.000000, 113.000000, "BPS");
	TextDrawFont(PublicTD[3], 2);
	TextDrawLetterSize(PublicTD[3], 0.916665, 5.400002);
	TextDrawTextSize(PublicTD[3], 400.000000, 17.000000);
	TextDrawSetOutline(PublicTD[3], 0);
	TextDrawSetShadow(PublicTD[3], 0);
	TextDrawAlignment(PublicTD[3], 1);
	TextDrawColor(PublicTD[3], 872363007);
	TextDrawBackgroundColor(PublicTD[3], 255);
	TextDrawBoxColor(PublicTD[3], 50);
	TextDrawUseBox(PublicTD[3], 0);
	TextDrawSetProportional(PublicTD[3], 1);
	TextDrawSetSelectable(PublicTD[3], 0);

	PublicTD[4] = TextDrawCreate(50.000000, 170.000000, "_");
	TextDrawFont(PublicTD[4], 1);
	TextDrawLetterSize(PublicTD[4], 0.000000, 6.000000);
	TextDrawTextSize(PublicTD[4], 230.000000, 17.000000);
	TextDrawSetOutline(PublicTD[4], 1);
	TextDrawSetShadow(PublicTD[4], 0);
	TextDrawAlignment(PublicTD[4], 1);
	TextDrawColor(PublicTD[4], -1);
	TextDrawBackgroundColor(PublicTD[4], 255);
	TextDrawBoxColor(PublicTD[4], 505290495);
	TextDrawUseBox(PublicTD[4], 1);
	TextDrawSetProportional(PublicTD[4], 1);
	TextDrawSetSelectable(PublicTD[4], 0);

	PublicTD[5] = TextDrawCreate(50.000000, 240.000000, "_");
	TextDrawFont(PublicTD[5], 1);
	TextDrawLetterSize(PublicTD[5], 0.000000, 6.000000);
	TextDrawTextSize(PublicTD[5], 230.000000, 0.000000);
	TextDrawSetOutline(PublicTD[5], 1);
	TextDrawSetShadow(PublicTD[5], 0);
	TextDrawAlignment(PublicTD[5], 1);
	TextDrawColor(PublicTD[5], -1);
	TextDrawBackgroundColor(PublicTD[5], 255);
	TextDrawBoxColor(PublicTD[5], 505290495);
	TextDrawUseBox(PublicTD[5], 1);
	TextDrawSetProportional(PublicTD[5], 1);
	TextDrawSetSelectable(PublicTD[5], 0);

	PublicTD[6] = TextDrawCreate(50.000000, 170.000000, "_");
	TextDrawFont(PublicTD[6], 1);
	TextDrawLetterSize(PublicTD[6], 0.000000, 1.749994);
	TextDrawTextSize(PublicTD[6], 230.000000, 0.000000);
	TextDrawSetOutline(PublicTD[6], 1);
	TextDrawSetShadow(PublicTD[6], 0);
	TextDrawAlignment(PublicTD[6], 1);
	TextDrawColor(PublicTD[6], -1);
	TextDrawBackgroundColor(PublicTD[6], 255);
	TextDrawBoxColor(PublicTD[6], 872363007);
	TextDrawUseBox(PublicTD[6], 1);
	TextDrawSetProportional(PublicTD[6], 1);
	TextDrawSetSelectable(PublicTD[6], 0);

	PublicTD[7] = TextDrawCreate(55.000000, 170.000000, "NICK:");
	TextDrawFont(PublicTD[7], 2);
	TextDrawLetterSize(PublicTD[7], 0.300000, 1.600000);
	TextDrawTextSize(PublicTD[7], 230.000000, 0.000000);
	TextDrawSetOutline(PublicTD[7], 0);
	TextDrawSetShadow(PublicTD[7], 0);
	TextDrawAlignment(PublicTD[7], 1);
	TextDrawColor(PublicTD[7], 255);
	TextDrawBackgroundColor(PublicTD[7], 255);
	TextDrawBoxColor(PublicTD[7], 50);
	TextDrawUseBox(PublicTD[7], 0);
	TextDrawSetProportional(PublicTD[7], 1);
	TextDrawSetSelectable(PublicTD[7], 0);

	PublicTD[8] = TextDrawCreate(50.000000, 240.000000, "_");
	TextDrawFont(PublicTD[8], 1);
	TextDrawLetterSize(PublicTD[8], 0.000000, 1.749994);
	TextDrawTextSize(PublicTD[8], 230.000000, 0.000000);
	TextDrawSetOutline(PublicTD[8], 1);
	TextDrawSetShadow(PublicTD[8], 0);
	TextDrawAlignment(PublicTD[8], 1);
	TextDrawColor(PublicTD[8], -1);
	TextDrawBackgroundColor(PublicTD[8], 255);
	TextDrawBoxColor(PublicTD[8], 872363007);
	TextDrawUseBox(PublicTD[8], 1);
	TextDrawSetProportional(PublicTD[8], 1);
	TextDrawSetSelectable(PublicTD[8], 0);

	PublicTD[9] = TextDrawCreate(55.000000, 240.000000, "Senha:");
	TextDrawFont(PublicTD[9], 2);
	TextDrawLetterSize(PublicTD[9], 0.300000, 1.600000);
	TextDrawTextSize(PublicTD[9], 230.000000, 0.000000);
	TextDrawSetOutline(PublicTD[9], 0);
	TextDrawSetShadow(PublicTD[9], 0);
	TextDrawAlignment(PublicTD[9], 1);
	TextDrawColor(PublicTD[9], 255);
	TextDrawBackgroundColor(PublicTD[9], 255);
	TextDrawBoxColor(PublicTD[9], 50);
	TextDrawUseBox(PublicTD[9], 0);
	TextDrawSetProportional(PublicTD[9], 1);
	TextDrawSetSelectable(PublicTD[9], 0);

	PublicTD[10] = TextDrawCreate(49.750000, 312.000000, "ld_dual:white");
	TextDrawFont(PublicTD[10], 4);
	TextDrawLetterSize(PublicTD[10], 0.600000, 2.000000);
	TextDrawTextSize(PublicTD[10], 181.000000, 38.500000);
	TextDrawSetOutline(PublicTD[10], 1);
	TextDrawSetShadow(PublicTD[10], 0);
	TextDrawAlignment(PublicTD[10], 1);
	TextDrawColor(PublicTD[10], 872363007);
	TextDrawBackgroundColor(PublicTD[10], 255);
	TextDrawBoxColor(PublicTD[10], 50);
	TextDrawUseBox(PublicTD[10], 1);
	TextDrawSetProportional(PublicTD[10], 1);
	TextDrawSetSelectable(PublicTD[10], 1);

	PublicTD[11] = TextDrawCreate(138.000000, 319.000000, "CONECTAR");
	TextDrawFont(PublicTD[11], 2);
	TextDrawLetterSize(PublicTD[11], 0.395832, 2.299998);
	TextDrawTextSize(PublicTD[11], 230.000000, 0.000000);
	TextDrawSetOutline(PublicTD[11], 0);
	TextDrawSetShadow(PublicTD[11], 0);
	TextDrawAlignment(PublicTD[11], 2);
	TextDrawColor(PublicTD[11], 255);
	TextDrawBackgroundColor(PublicTD[11], 255);
	TextDrawBoxColor(PublicTD[11], 50);
	TextDrawUseBox(PublicTD[11], 0);
	TextDrawSetProportional(PublicTD[11], 1);
	TextDrawSetSelectable(PublicTD[11], 0);

	PublicTD[12] = TextDrawCreate(139.250000, 317.750000, "CONECTAR");
	TextDrawFont(PublicTD[12], 2);
	TextDrawLetterSize(PublicTD[12], 0.395832, 2.299998);
	TextDrawTextSize(PublicTD[12], 230.000000, 0.000000);
	TextDrawSetOutline(PublicTD[12], 0);
	TextDrawSetShadow(PublicTD[12], 0);
	TextDrawAlignment(PublicTD[12], 2);
	TextDrawColor(PublicTD[12], -1);
	TextDrawBackgroundColor(PublicTD[12], 255);
	TextDrawBoxColor(PublicTD[12], 50);
	TextDrawUseBox(PublicTD[12], 0);
	TextDrawSetProportional(PublicTD[12], 1);
	TextDrawSetSelectable(PublicTD[12], 0);

	PublicTD[13] = TextDrawCreate(293.000000, 81.000000, "_");
	TextDrawFont(PublicTD[13], 1);
	TextDrawLetterSize(PublicTD[13], 0.000000, 34.549991);
	TextDrawTextSize(PublicTD[13], 608.500000, 0.000000);
	TextDrawSetOutline(PublicTD[13], 1);
	TextDrawSetShadow(PublicTD[13], 0);
	TextDrawAlignment(PublicTD[13], 1);
	TextDrawColor(PublicTD[13], -1);
	TextDrawBackgroundColor(PublicTD[13], 255);
	TextDrawBoxColor(PublicTD[13], 505290495);
	TextDrawUseBox(PublicTD[13], 1);
	TextDrawSetProportional(PublicTD[13], 1);
	TextDrawSetSelectable(PublicTD[13], 0);

	PublicTD[14] = TextDrawCreate(293.000000, 81.000000, "_");
	TextDrawFont(PublicTD[14], 1);
	TextDrawLetterSize(PublicTD[14], 0.000000, 2.549993);
	TextDrawTextSize(PublicTD[14], 608.500000, 0.000000);
	TextDrawSetOutline(PublicTD[14], 1);
	TextDrawSetShadow(PublicTD[14], 0);
	TextDrawAlignment(PublicTD[14], 1);
	TextDrawColor(PublicTD[14], -1);
	TextDrawBackgroundColor(PublicTD[14], 255);
	TextDrawBoxColor(PublicTD[14], 872363007);
	TextDrawUseBox(PublicTD[14], 1);
	TextDrawSetProportional(PublicTD[14], 1);
	TextDrawSetSelectable(PublicTD[14], 0);

	PublicTD[15] = TextDrawCreate(452.000000, 83.000000, "NOVIDADES");
	TextDrawFont(PublicTD[15], 2);
	TextDrawLetterSize(PublicTD[15], 0.566666, 2.549993);
	TextDrawTextSize(PublicTD[15], 608.500000, 0.000000);
	TextDrawSetOutline(PublicTD[15], 0);
	TextDrawSetShadow(PublicTD[15], 0);
	TextDrawAlignment(PublicTD[15], 2);
	TextDrawColor(PublicTD[15], 255);
	TextDrawBackgroundColor(PublicTD[15], 255);
	TextDrawBoxColor(PublicTD[15], 872363007);
	TextDrawUseBox(PublicTD[15], 0);
	TextDrawSetProportional(PublicTD[15], 1);
	TextDrawSetSelectable(PublicTD[15], 0);

	PublicTD[16] = TextDrawCreate(450.000000, 81.000000, "NOVIDADES");
	TextDrawFont(PublicTD[16], 2);
	TextDrawLetterSize(PublicTD[16], 0.566666, 2.549993);
	TextDrawTextSize(PublicTD[16], 608.500000, 0.000000);
	TextDrawSetOutline(PublicTD[16], 0);
	TextDrawSetShadow(PublicTD[16], 0);
	TextDrawAlignment(PublicTD[16], 2);
	TextDrawColor(PublicTD[16], -1);
	TextDrawBackgroundColor(PublicTD[16], 255);
	TextDrawBoxColor(PublicTD[16], 872363007);
	TextDrawUseBox(PublicTD[16], 0);
	TextDrawSetProportional(PublicTD[16], 1);
	TextDrawSetSelectable(PublicTD[16], 0);

	PublicTD[17] = TextDrawCreate(303.000000, 127.000000, "Lorem ipsum dolor sit amet, consectetur~n~adipiscing elit. Pellentesque iaculis,~n~orci at bibendum lobortis, metus justo~n~vehi");
	TextDrawFont(PublicTD[17], 2);
	TextDrawLetterSize(PublicTD[17], 0.275000, 1.700000);
	TextDrawTextSize(PublicTD[17], 597.500000, 11.500000);
	TextDrawSetOutline(PublicTD[17], 0);
	TextDrawSetShadow(PublicTD[17], 0);
	TextDrawAlignment(PublicTD[17], 1);
	TextDrawColor(PublicTD[17], 255);
	TextDrawBackgroundColor(PublicTD[17], 255);
	TextDrawBoxColor(PublicTD[17], 50);
	TextDrawUseBox(PublicTD[17], 1);
	TextDrawSetProportional(PublicTD[17], 1);
	TextDrawSetSelectable(PublicTD[17], 0);

	return 1;
}

public OnFilterScriptExit()
{
	TextDrawDestroy(PublicTD[0]);
	TextDrawDestroy(PublicTD[1]);
	TextDrawDestroy(PublicTD[2]);
	TextDrawDestroy(PublicTD[3]);
	TextDrawDestroy(PublicTD[4]);
	TextDrawDestroy(PublicTD[5]);
	TextDrawDestroy(PublicTD[6]);
	TextDrawDestroy(PublicTD[7]);
	TextDrawDestroy(PublicTD[8]);
	TextDrawDestroy(PublicTD[9]);
	TextDrawDestroy(PublicTD[10]);
	TextDrawDestroy(PublicTD[11]);
	TextDrawDestroy(PublicTD[12]);
	TextDrawDestroy(PublicTD[13]);
	TextDrawDestroy(PublicTD[14]);
	TextDrawDestroy(PublicTD[15]);
	TextDrawDestroy(PublicTD[16]);
	TextDrawDestroy(PublicTD[17]);
	return 1;
}

public OnPlayerConnect(playerid)
{
	PlayerTD[playerid][0] = CreatePlayerTextDraw(playerid, 55.000000, 200.500000, "<TEMPLATE_PLAYERNAME>");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][0], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][0], 0.300000, 1.600000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][0], 230.000000, 0.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][0], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][0], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][0], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][0], -741092353);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][0], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][0], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][0], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][0], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][0], 0);

	PlayerTD[playerid][1] = CreatePlayerTextDraw(playerid, 55.000000, 260.000000, "........................");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][1], 1);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][1], 0.595830, 2.949994);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][1], 230.000000, 0.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][1], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][1], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][1], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][1], -741092353);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][1], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][1], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][1], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][1], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][1], 0);

	PlayerTD[playerid][3] = CreatePlayerTextDraw(playerid, 46.750000, 260.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][3], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][3], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][3], 186.500000, 38.500000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][3], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][3], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][3], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][3], 16711680);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][3], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][3], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][3], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][3], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][3], 1);

	return 1;
}

public OnPlayerDisconnect(playerid, reason)
{
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][0]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][1]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][3]);
	return 1;
}

public OnPlayerCommandText(playerid, cmdtext[])
{
	if(!strcmp(cmdtext, "/tdtest", true))
	{
		TextDrawShowForPlayer(playerid, PublicTD[0]);
		TextDrawShowForPlayer(playerid, PublicTD[1]);
		TextDrawShowForPlayer(playerid, PublicTD[2]);
		TextDrawShowForPlayer(playerid, PublicTD[3]);
		TextDrawShowForPlayer(playerid, PublicTD[4]);
		TextDrawShowForPlayer(playerid, PublicTD[5]);
		TextDrawShowForPlayer(playerid, PublicTD[6]);
		TextDrawShowForPlayer(playerid, PublicTD[7]);
		TextDrawShowForPlayer(playerid, PublicTD[8]);
		TextDrawShowForPlayer(playerid, PublicTD[9]);
		TextDrawShowForPlayer(playerid, PublicTD[10]);
		TextDrawShowForPlayer(playerid, PublicTD[11]);
		TextDrawShowForPlayer(playerid, PublicTD[12]);
		TextDrawShowForPlayer(playerid, PublicTD[13]);
		TextDrawShowForPlayer(playerid, PublicTD[14]);
		TextDrawShowForPlayer(playerid, PublicTD[15]);
		TextDrawShowForPlayer(playerid, PublicTD[16]);
		TextDrawShowForPlayer(playerid, PublicTD[17]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][0]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][1]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][3]);
		SelectTextDraw(playerid, 0xFF0000FF);
		return 1;
	}
	return 0;
}
